baseURL = "https://sacoco.xyz"
languageCode = "en-us"
title = "sacoco"
theme = "awesome-identity"


## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpeg"
  firstname = "Santiago"
  lastname = "Correa"
  title = "Software engineer"
  bio = """Geek guy who likes travel"""



## Contacts Configurations
[params.contacts]
  email = "sacoco99@gmail.com"
  github = "sacoco"
  linkedin = "sacoco"
  stackoverflow = "13254836"


## Footer Configurations
[params.footer]
  copyright = "© 1999-2020 Bogotá Colombia. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = false
